"""
design-agent – CogniOps Design-Time Agent.

Batch/scheduled service that:
  1. Builds analysis context from BQ metrics + GCS config
  2. Runs ADK LlmAgent for structural analysis
  3. Validates proposal (deterministic)
  4. Stores proposal in GCS + creates GitHub Issue

Endpoints:
  POST /run          – Trigger analysis (Cloud Scheduler or manual)
  GET  /health       – Liveness probe
  GET  /agent/info   – ADK agent metadata

Trigger: Cloud Scheduler HTTP POST (weekly) or manual workflow_dispatch.
"""

from __future__ import annotations

import json
import logging
import os
import time
from datetime import datetime, timezone

from fastapi import FastAPI
from fastapi.responses import JSONResponse
from google.adk.runners import InMemoryRunner
from google.genai import types

import httpx

from agent.design_agent import design_agent
from agent.tools.validator import validate_proposal
from models.schemas import DesignProposal, ValidationResult

# ── Logging ──────────────────────────────────────────────────────────

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
logging.basicConfig(
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    level=getattr(logging, LOG_LEVEL, logging.INFO),
)
logger = logging.getLogger("design-agent")

# ── Config ───────────────────────────────────────────────────────────

CONFIG_BUCKET = os.getenv("CONFIG_BUCKET", "")
PROPOSALS_PREFIX = os.getenv("PROPOSALS_PREFIX", "proposals/design")
GITHUB_REPO = os.getenv("GITHUB_REPO", "")
CONTEXT_WINDOW_DAYS = int(os.getenv("CONTEXT_WINDOW_DAYS", "30"))

# ── FastAPI app ──────────────────────────────────────────────────────

app = FastAPI(
    title="CogniOps Design-Time Agent",
    description="Structural synthesis — metric analysis and improvement proposals",
    version="0.1.0",
)

# ── ADK Runner ───────────────────────────────────────────────────────

runner = InMemoryRunner(agent=design_agent, app_name="cogniops_design")
runner.auto_create_session = True


# ── GCS Helpers ──────────────────────────────────────────────────────


def _write_gcs_json(path: str, data: dict) -> str | None:
    """Write JSON to GCS. Returns gs:// URI on success, None on failure."""
    if not CONFIG_BUCKET:
        logger.warning("CONFIG_BUCKET not set — skipping GCS write")
        return None
    try:
        from google.cloud import storage

        client = storage.Client()
        bucket = client.bucket(CONFIG_BUCKET)
        blob = bucket.blob(path)
        blob.upload_from_string(
            json.dumps(data, indent=2, default=str),
            content_type="application/json",
        )
        uri = f"gs://{CONFIG_BUCKET}/{path}"
        logger.info("Wrote proposal to %s", uri)
        return uri
    except Exception:
        logger.warning("GCS write failed for %s", path, exc_info=True)
        return None


# ── GitHub Issue Creation ────────────────────────────────────────────


def _create_github_issue(proposal: dict) -> str | None:
    """Create a GitHub Issue with proposal summary. Returns issue URL or None."""
    token = os.getenv("GITHUB_TOKEN", "")
    if not token or not GITHUB_REPO:
        logger.info("GITHUB_TOKEN or GITHUB_REPO not set — skipping issue creation")
        return None
    try:
        title = f"[Design Proposal] {proposal['intent']}"
        scenarios = ", ".join(proposal.get("target_scenarios", []))
        changes_text = "\n".join(
            f"- **{ch['change_type']}** on `{ch['target_file']}`: {ch['description']}"
            for ch in proposal.get("changes", [])
        )
        impact_text = "\n".join(
            f"- {imp['metric_name']}: {imp['estimated_change']} (confidence: {imp['confidence']})"
            for imp in proposal.get("expected_impact", [])
        )
        body = (
            f"## Design Proposal: {proposal['intent']}\n\n"
            f"**Proposal ID:** `{proposal['proposal_id']}`\n"
            f"**Scenarios:** {scenarios}\n\n"
            f"### Analysis\n{proposal.get('analysis_summary', 'N/A')}\n\n"
            f"### Proposed Changes\n{changes_text}\n\n"
            f"### Expected Impact\n{impact_text}\n\n"
            f"---\n*Auto-generated by CogniOps Design-Time Agent. "
            f"Requires human review before implementation.*"
        )

        resp = httpx.post(
            f"https://api.github.com/repos/{GITHUB_REPO}/issues",
            headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
            },
            json={
                "title": title,
                "body": body,
                "labels": ["design-proposal", "automated"],
            },
            timeout=30,
        )
        resp.raise_for_status()
        issue_url = resp.json().get("html_url", "")
        logger.info("Created GitHub Issue: %s", issue_url)
        return issue_url
    except Exception:
        logger.warning("GitHub Issue creation failed", exc_info=True)
        return None


# ── Pipeline ─────────────────────────────────────────────────────────


async def _run_pipeline(
    scenarios: list[str] | None = None,
    variant_filter: str | None = None,
) -> dict:
    """Execute the full design-time analysis pipeline.

    Returns:
        Result dict with proposal (if generated), validation, and storage details.
    """
    t_start = time.monotonic()

    # Build the user message for the LLM
    focus = f" focusing on scenarios: {', '.join(scenarios)}" if scenarios else ""
    variant_instruction = ""
    if variant_filter:
        variant_instruction = (
            f" Use variant_filter='{variant_filter}' when calling build_context"
            " to filter runs by variant label."
        )
    user_message = (
        f"Analyze the current CogniOps metrics (last {CONTEXT_WINDOW_DAYS} days)"
        f"{focus}. "
        "First call build_context to gather metrics and configuration"
        f"{variant_instruction}, "
        "then analyze the data for optimization opportunities. "
        "Even if metrics are stable, look for ways to improve them — "
        "for example, reducing MTTD or MTTR through polling interval adjustments, "
        "threshold tuning, or workflow improvements. "
        "Call generate_proposal with specific improvements, "
        "or call no_proposal_needed only if metrics are already at theoretical optimum."
    )

    # Run through ADK
    proposal_data = None
    no_proposal_reason = None
    all_events = []

    try:
        async for event in runner.run_async(
            user_id="design-agent-scheduler",
            session_id=None,
            new_message=types.Content(
                role="user",
                parts=[types.Part.from_text(text=user_message)],
            ),
        ):
            all_events.append(event)
            for fn_resp in event.get_function_responses():
                response = fn_resp.response
                if isinstance(response, dict):
                    if response.get("status") == "proposal_generated":
                        proposal_data = response.get("proposal")
                    elif response.get("status") == "no_proposal_needed":
                        no_proposal_reason = response.get("reason")
    except Exception:
        logger.error("ADK pipeline failed", exc_info=True)
        return {
            "status": "error",
            "message": "ADK pipeline failed — no proposal generated",
            "duration_sec": round(time.monotonic() - t_start, 2),
        }

    # No proposal needed
    if no_proposal_reason:
        return {
            "status": "no_changes",
            "reason": no_proposal_reason,
            "duration_sec": round(time.monotonic() - t_start, 2),
        }

    # No proposal data extracted
    if not proposal_data:
        return {
            "status": "no_output",
            "message": "ADK produced no proposal output",
            "duration_sec": round(time.monotonic() - t_start, 2),
        }

    # Validate
    validation = validate_proposal(proposal_data)
    proposal_data["validation"] = validation

    if not validation["valid"]:
        logger.warning("Proposal failed validation: %s", validation["errors"])
        return {
            "status": "validation_failed",
            "validation": validation,
            "duration_sec": round(time.monotonic() - t_start, 2),
        }

    # Store in GCS
    proposal_id = proposal_data.get("proposal_id", "unknown")
    gcs_path = f"{PROPOSALS_PREFIX}/{proposal_id}.json"
    gcs_uri = _write_gcs_json(gcs_path, proposal_data)

    # Create GitHub Issue
    issue_url = _create_github_issue(proposal_data)

    duration = round(time.monotonic() - t_start, 2)
    return {
        "status": "proposal_stored",
        "proposal_id": proposal_id,
        "intent": proposal_data.get("intent", ""),
        "gcs_uri": gcs_uri,
        "github_issue": issue_url,
        "validation": validation,
        "duration_sec": duration,
    }


# ── Endpoints ────────────────────────────────────────────────────────


@app.post("/run")
async def run_analysis(
    scenarios: list[str] | None = None,
) -> JSONResponse:
    """Trigger a design-time analysis.

    Optional body: {"scenarios": ["s3", "ss2"]} to focus on specific scenarios.
    """
    result = await _run_pipeline(scenarios=scenarios)
    status_code = 200 if result["status"] in ("proposal_stored", "no_changes") else 500
    return JSONResponse(content=result, status_code=status_code)


@app.get("/health")
async def health() -> dict:
    return {"status": "ok", "service": "design-agent"}


@app.get("/agent/info")
async def agent_info() -> dict:
    return {
        "agent_name": design_agent.name,
        "model": design_agent.model,
        "tools": [t.__name__ for t in design_agent.tools],
        "version": app.version,
    }
